queue_rules:
  - name: urgent
    merge_conditions:
      - check-success=test_my_app/build_and_test

  - name: default
    merge_conditions:
      - check-success=test_my_app/build_and_test

pull_request_rules:
  - name: move to urgent queue when label urgent
    conditions:
      - base=main
      - label=urgent
    actions:
      queue:
        name: urgent

  - name: merge using the default queue after running the CI checks
    conditions:
      - base=main
      - check-success=test_my_app/build_and_test
      - label!=urgent
    actions:
      queue:
        name: default
